[package]
authors = ["Loi Tran"]

name = "revelation"
description = "Revelation helps developers discover hidden patterns in code."
edition = "2024"
version = "0.0.1"

license = "MIT OR Apache-2.0"

documentation = "https://docs.rs/revelation"
homepage = "https://kb-blog-primetimetran.vercel.app/"
repository = "https://github.com/primetimetran/revelation"
keywords = ["virtualization", "visualization", "filesystem", "development-tools", "os"]
categories = ["virtualization", "visualization", "filesystem", "development-tools", "os"]

[dependencies]
syn.workspace = true
clap.workspace = true
quote.workspace = true
regex.workspace = true
walkdir.workspace = true
swc_core.workspace = true
prettyplease.workspace = true
regex-syntax.workspace = true
serde.workspace = true
serde_json.workspace = true
proc-macro2 = { version = "1", features = ["span-locations"] }

# OPTION 3:

# OPTION 2: "Crate-Specific" Semantic Versioning
# swc_common = { version = "0.33" }
# Use the 23.x versions for EVERYTHING
# swc_common      = "0.33.26" # Wait, see note below!
# swc_ecma_ast    = "0.144.0" # You must match the minor versions
# swc_ecma_parser = "0.170.0"
# swc_ecma_visit  = "0.144.0"

# OPTION 1: "SWC Project" Release Version
# swc_common      = "23.0.2"
# swc_ecma_ast    = "23.0.1"
# swc_ecma_parser = "23.0.0"
# swc_ecma_lexer  = "23.0.0"
# swc_ecma_visit  = "23.0.0"

# INCASE
# - You don't remember every syntax
# swc_ecma_parser = { path = "../../../swc/crates/swc_ecma_parser" }
